pipeline {
    agent any

    environment {
        IMAGE_NAME = "pruthvirajpha/devops-app"
        IMAGE_TAG  = "latest"
        AWS_REGION = "ap-south-1"
        CLUSTER_NAME = "devops-project-eks"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/PruthvirajPhadatare/Node-js-DevOps-Project.git'
            }
        }

        stage('Configure kubectl') {
            steps {
                sh """
                    aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                    kubectl set image deployment/devops-app devops-app=$IMAGE_NAME:$IMAGE_TAG --record
                """
            }
        }
    }
}
